[package]
name = "multi-map"
version = "1.0.0"
authors = ["theJPster <github@thejpster.org.uk>"]
description = "Like a std::collection::HashMap, but allows you to use either of two different keys to retrieve items."
license = "MIT"

[dependencies]
